language: php
php:
  - 5.4
before_script:
  - travis_retry composer self-update && composer --version
  - composer install --prefer-source --optimize-autoloader
script:
  - vendor/bin/pharmacist verify
