parameters:
    redis.scheme: "tcp"
    redis.host: "localhost"
    redis.port: 6379

    defaultQueue: null

services:
    redisClient:
        class: Predis\Client
        arguments:
            -
                scheme: "%redis.scheme%"
                host: "%redis.host%"
                port: "%redis.port%"

    redisQueue:
        class: Silktide\Queueball\Redis\Queue
        arguments:
            - "@redisClient"
            - "@silktide_queueball.messageFactory"
            - "%defaultQueue%"

    # set the sqs queue to be default
    silktide_queueball.defaultQueue:
        aliasOf: "@redisQueue"

